version: '3.0'
services:
  db:
    container_name: es_container
    #image: eventstore/eventstore:20.10.1-buster-slim
    image: eventstore/eventstore:20.10.2-buster-slim
    restart: always
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 9000m
        reservations:
          cpus: '0.1'
          memory: 4000m
volumes:
  eventstore-volume-data:
  eventstore-volume-logs: